###apollo配置
app:
  id: SampleApp
apollo:
  meta: http://192.168.1.106:8080
  cluster: DEV
  bootstrap:
    enable: true
    namespaces: application
    eagerLoad:
      enbale: false

### 架构部署图https://www.apolloconfig.com/#/zh/deployment/deployment-architecture